### ISSUE TITLE
Add Mypy and Coverage.py

### ISSUE THREAD

**Issue by areibman** [AgentOps-AI/agentops#14]
## 🚀 Feature Request

**💡 Got a brilliant idea?**
Currently, our test coverage is not being tracked. Also, we want to abide by Mypy typing

**🤔 Is your feature request related to a problem?**
We don't have adequate coverage reporting.

**🎉 Describe the solution you'd like**
Add mypy and coverage.py to our tox file.

**Comment by dot-agi** [comment]
Working on this in this PR #153

**Comment by siyangqiu** [comment]
Merged. Thanks @the-praxs
