### ISSUE TITLE
Session Drill Down page does not refresh to the selected issue

### ISSUE THREAD

**Issue by adunato** [AgentOps-AI/agentops#167]
## 🐛 Bug Report

**🔎 Describe the Bug**
When refreshing the drill down page, either via refresh button or browser refresh, the page still shows the previously used session rather than the latest. The session tab however, shows the latest session as selected. User must select another session and then select again the latest session in the session tab in order to show the latest session.

**🔄 Reproduction Steps**
1. Generate a new session
2. Go to session drill down page
3. Hit refresh button

**🙁 Expected Behavior**
After refreshing the drill down page should show the latest session/

**📸 Screenshots**
![image](https://github.com/AgentOps-AI/agentops/assets/7783232/988edeff-86d3-4923-8a87-8aa8c219fd07)

Thank you for helping us improve Agentops!

**Comment by areibman** [comment]
Surprised we didn't see this earlier, taking a look at it now. Thanks @adunato

**Comment by siyangqiu** [comment]
@adunato, I think what you are saying makes a lot of sense! However, it used to do exactly as you wanted and we had folks complain that refreshing would take them away from the session they were looking at. Would a button that takes you to the latest session solve your issue?

Note: the refresh button refreshes the current session you are looking at - so if you log new events they will show up (the SDK sends events every 30 seconds by default, so it won't be immediate unless you change the config).

**Comment by adunato** [comment]
@siyangqiu thanks, it makes sense that retaining the current session is the preferred behavior but there is an issue with inconsistency between displayed session and session selected in the sessions tab.

See below my comment on this. 

The session tab however, shows the latest session as selected. User must select another session and then select again the latest session in the session tab in order to show the latest session.

**Comment by siyangqiu** [comment]
I see! Let me look into that!

**Comment by siyangqiu** [comment]
@adunato Can you confirm if the bug still exists for you? I made some changes over the last week that involves the session selector component, and I suspect I may have inadvertently fixed it

**Comment by adunato** [comment]
@siyangqiu it now works after refreshing the page (F5), but if I open the dashboard after running a new session, the behaviour is same as before, the new session appears as selected in the session selector but the previously open session is displayed.

![image](https://github.com/AgentOps-AI/agentops/assets/7783232/e6bb1abd-44e8-4ede-ba39-68e62698cc6c)

**Comment by siyangqiu** [comment]
That's odd. I can't seem to reproduce it. What browser are you using?

**Comment by adunato** [comment]
@siyangqiu Chrome. I tried again and it did update the session tab albeit with a couple of seconds of delay. It's fine from my point of view, happy to close.

**Comment by siyangqiu** [comment]
@adunato Once again, thanks for the report! There are some performance improvements and UI tweaks on the way shortly, including a button that takes you to the latest session. That delay you see also should be much shorter soon!
