### ISSUE TITLE
Add color and highlighting to session start link + verbosity level

### ISSUE THREAD

**Issue by areibman** [AgentOps-AI/agentops#200]
## 🚀 Feature Request

**💡 Got a brilliant idea?**
Currently, we log the link to the session. But it's drowned out because it's not colored or bolded. I've seen a few other session-style analytics tools do it well
<img width="1457" alt="image" src="https://github.com/AgentOps-AI/agentops/assets/14807319/4ee37676-a101-455a-89c9-a63f1485a219">

In addition, we should try to add a `-q` flag or verbosity level in .env so that users can turn off extraneous logging

**Comment by braelyn-ai** [comment]
We do have a verbosity flag available. More info in our [docs](https://docs.agentops.ai/v1/usage/environment-variables)
