### ISSUE TITLE
instrument_llm_calls=False + stop_instrumenting() will raise on missing llm_tracker

### ISSUE THREAD

**Issue by mbarnathan** [AgentOps-AI/agentops#256]
## 🐛 Bug Report

**🔎 Describe the Bug**
If you start up an agentops client with instrument_llm_calls false and stop_instrumenting() gets called, whether implicitly via Crew/Autogen or explicitly by the caller, client.py will try to reference an undefined self.llm_tracker member and throw. (Even though it is checked for truthiness, only getattr/hasattr will work when the value isn't set at all)

The fix is to explicitly set llm_tracker to None in the constructor, which will make the check later work properly with a falsy value. I will submit a fix.

**Comment by heethjain21** [comment]
Was taking a look at this issue, and it seems like it has been already resolved.


When the PR was created https://github.com/AgentOps-AI/agentops/pull/257, the code was
```
def stop_instrumenting(self):
    if self.llm_tracker:
        self.llm_tracker.stop_instrumenting()
```

However, now the [current code](https://github.com/AgentOps-AI/agentops/blob/39958340fa765d8671dda2b5a7053e49435902cf/agentops/client.py#L362) now has check with `is not None`:
```
def stop_instrumenting(self):
    if self._llm_tracker is not None:
        self._llm_tracker.stop_instrumenting()
```

Can anyone please confirm whether there is still more to solving this issue apart from this or has it been resolved?

**Comment by HowieG** [comment]
Thanks @mbarnathan for reporting and @heethjain21 for following up.

@siyangqiu says this should be a non-issue after our refactor. Tagging @bboynton97 to double check.
https://github.com/AgentOps-AI/agentops/pull/257#issuecomment-2290399028

Though Braelyn did say that her PR was not related to this one
https://github.com/AgentOps-AI/agentops/pull/368#issue-2476756793

**Comment by braelyn-ai** [comment]
This should be resolved by that refactor! I'm marking this issue as closed, thank you everyone for contributing 🫶
