### ISSUE TITLE
Open Source LLMs using ollama

### ISSUE THREAD

**Issue by Shuaib11-Github** [AgentOps-AI/agentops#265]
## 🐛 Bug Report

**🔎 Describe the Bug**
Give a clear and concise description of the bug.

I tried to run the open source model using ollama but in the AgentsOps dashboard it is not posting the llm calls. Can you fix this for any open source LLM used either through ollama or Groq or some other way.

**🔄 Reproduction Steps**
List the steps to reproduce the behavior.

**🙁 Expected Behavior**
Describe what you expected to happen.

Integrate the open source LLMs also to post the data of what's happening under the hood.

**📸 Screenshots**
If applicable, add screenshots to help explain the problem.

**🔍 Additional Context**
Provide any other context about the problem here.

Thank you for helping us improve Agentops!

**Comment by sprajosh** [comment]
Hey, Ollama support was added recently. You can use it by pulling the github repo and installing the manually to get the latest changes.

To install the latest version of agentops, you can follow these steps

1. Clone the project
```
git clone git@github.com:AgentOps-AI/agentops.git
```
2. ```cd agentops```
3. ```pip install -e .```

**Comment by albertkimjunior** [comment]
Hey @sprajosh I'm also currently reviewing this bug as well, I'll let you know if there's anything I find

**Comment by sprajosh** [comment]
@albertkimjunior I think you misunderstood what I said. I have already added Ollama support. Since the version has not been updated, I was suggesting maybe pull the code from github and install the latest package manually.

Or, is there a bug in the ollama models?

**Comment by albertkimjunior** [comment]
@sprajosh No I understood. I am also looking at the Ollama support pull request that @siyangqiu approved to double-check if there are any possible issues.

**Comment by siyangqiu** [comment]
Ollama support was merged to the main branch, but it is not currently released to pypi. There is an unrelated bug blocking the release ☹️. We'll have it released shortly

**Comment by siyangqiu** [comment]
Ollama support is release in v0.2.5
