### ISSUE TITLE
API key in docs component

### ISSUE THREAD

**Issue by braelyn-ai** [AgentOps-AI/agentops#267]
Create a react component within Mintlify that can display the user's API key in the docs. Clicking it should copy the key.

Original Branch: https://github.com/AgentOps-AI/AgentOps.Next/pull/161/files

**Comment by albertkimjunior** [comment]
@bboynton97
Blocked by [$$$](https://mintlify.com/pricing), current plan does not allow custom .js

**Comment by albertkimjunior** [comment]
actually, nah, I'd win

![nah](https://github.com/AgentOps-AI/agentops/assets/8823363/2ea969a4-ee70-4356-bde2-bd28430027a9)

will be fixed by discovery from #276 
@areibman

**Comment by albertkimjunior** [comment]
oh oops I just saw that I accidentally wrote a fix keyword in the description of the Github stars dynamic update PR that auto-closed this issue, I'll re-open it and then make some adjustments today
