### ISSUE TITLE
ModuleNotFoundError: No module named 'ollama'

### ISSUE THREAD

**Issue by AIAnytime** [AgentOps-AI/agentops#277]
Here is my code:
`from crewai import Agent, Task, Crew, Process
import os
from dotenv import load_dotenv

load_dotenv()

os.environ["OPENAI_API_KEY"] = os.getenv("OPENAI_API_KEY")

import agentops

agentops.init("", tags=["crewai-agent"])

researcher = Agent(
    role="Researcher",
    goal="Discover new insights",
    verbose=True,
    backstory=(
        "You are a world class researcher working on a major data science company"
    ),
    allow_delegation=False,
)

writer = Agent(
    role="Writer",
    goal="Create Engaging content",
    verbose=True,
    backstory=(
        "You are a famous technical writer, specialized on writing data related content"
    ),
    allow_delegation=False,
)

task1 = Task(
    description=("Investigate the latest AI trends"),
    expected_output="Investigate the latest AI trends",
    agent=researcher,
)
tast2 = Task(
    description=("Write a blog post on AI advancements"),
    expected_output="Write a detailed blog post",
    agent=writer,
)

crew = Crew(
    agents=[researcher, writer],
    tasks=[task1, tast2],
    verbose=True,
)

result = crew.kickoff()

print("The outputs have been compiled")
print("Result=> ", result)

agentops.end_session("Success")`

It gives me   import ollama
ModuleNotFoundError: No module named 'ollama'

I am not even using ollama.

**Comment by albertkimjunior** [comment]
@areibman hm

**Comment by AIAnytime** [comment]
any update? Poor docs, no solution.

**Comment by areibman** [comment]
> any update? Poor docs, no solution.

Hey @AIAnytime -- thought we replied. We're taking a look to see what's going on. Can you verify which version of AgentOps you're on?

**Comment by siyangqiu** [comment]
Please update to agentops v0.2.6 which contains the patch for this issue
