### ISSUE TITLE
langhchain version typo 

### ISSUE THREAD

**Issue by f1delius** [AgentOps-AI/agentops#280]
## 🐛 Bug Report

**🔎 Describe the Bug**
Can't install agentops[langchain] versions > 0.1.10

**🔄 Reproduction Steps**
pip install agentops[langchain]

**🙁 Expected Behavior**
In project.toml , langchain requirements is 1.19 which should be 0.1.19

**Comment by seshubonam** [comment]
+1

**Comment by HowieG** [comment]
Resolved by #366
