### ISSUE TITLE
TypeError

### ISSUE THREAD

**Issue by codingaslu** [AgentOps-AI/agentops#282]
TypeError: 'generator' object does not support the context manager protocol

**Comment by areibman** [comment]
Hey @codingaslu -- Can you give us some more context about how you ran into this error?
1. Which version of AgentOps are you running?
2. Are you using any frameworks like AutoGen or Crew?
3. Can you post a code snippet to replicate?

**Comment by codingaslu** [comment]
AgentOps Version:  AgentOps version 0.2.6.

Frameworks: CrewAI framework.

Issue: CrewAI agent works correctly, but after adding AgentOps initialization code, the CrewAI starts and gives this error.

**Comment by areibman** [comment]
> AgentOps Version: AgentOps version 0.2.6.
> 
> Frameworks: CrewAI framework.
> 
> Issue: CrewAI agent works correctly, but after adding AgentOps initialization code, the CrewAI starts and gives this error.

Gotcha. Can you make sure you're using the the CrewAI fork? 
```
pip uninstall crewai
pip install git+https://github.com/AgentOps-AI/crewAI.git@main
```
