### ISSUE TITLE
Groq support

### ISSUE THREAD

**Issue by acamenhas** [AgentOps-AI/agentops#283]
Hello,

I'm using Ollama via Groq, can I track those LLM calls with agentops?

Thank you

**Comment by areibman** [comment]
> Hello,
> 
> I'm using Ollama via Groq, can I track those LLM calls with agentops?
> 
> Thank you

We support Groq via our LiteLLM integration: https://docs.agentops.ai/v1/integrations/litellm

Also, if you use langchain groq, the langchain callback handler should work.

That said, we're planning on native Groq SDK support in the future.

**Comment by braelyn-ai** [comment]
Groq is now supported by AgentOps directly :)
