### ISSUE TITLE
Create a way to disable AgentOps functions entirely

### ISSUE THREAD

**Issue by areibman** [AgentOps-AI/agentops#349]
## 🚀 Feature Request

**💡 Got a brilliant idea?**
As we are adding AgentOps to more open source repos, there's an issue we may face where functions break and we don't have time to support fixes. For example:https://github.com/iyaja/llama-fs/issues/49

In this case, we should have a kill switch that turns off all AO functions and turns them into no-ops.

**🎉 Describe the solution you'd like**
We did something similar for multi-on-- have a handful of No-op functions that activate when a certain flag is set.

**Comment by heethjain21** [comment]
Created a PR: https://github.com/AgentOps-AI/agentops/pull/387

Please also assign to me (in case of any changes required)

**Comment by siyangqiu** [comment]
This issue should not have been created in the first place
