### ISSUE TITLE
Save all logs from AgentOps runs

### ISSUE THREAD

**Issue by areibman** [AgentOps-AI/agentops#350]
## Issue
Currently we save all AgentOps events. Would be great to just save all StandardOut

## 🐛 Bug Report
<img width="392" alt="image" src="https://github.com/user-attachments/assets/66d39aff-47cd-4b9c-b69b-fd05a1d07323">

**🔎 Describe the Bug**
When running the latest version of AgentOps, an agentops.log file appears. This isn't desired behavior unless specifically marked.

**Comment by areibman** [comment]
> ## 🐛 Bug Report
> <img alt="image" width="392" src="https://private-user-images.githubusercontent.com/14807319/356905011-66d39aff-47cd-4b9c-b69b-fd05a1d07323.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQxMDgyNzEsIm5iZiI6MTcyNDEwNzk3MSwicGF0aCI6Ii8xNDgwNzMxOS8zNTY5MDUwMTEtNjZkMzlhZmYtNDdjZC00YjljLWI2OWItZmQwNWExZDA3MzIzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE5VDIyNTI1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYyYmYyMDdiYjcyMGYyNGQ1ZDQ3NmRhNTVlZjkzZTQ2NzY0Mzk2MWJlNDI3MmM0YWVlZDE3MWUxYzI4MzM3MjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.qf9p2vKFTc69WIms4MrCl-h933mXiIByXMtolb04i7U">
> **🔎 Describe the Bug** When running the latest version of AgentOps, an agentops.log file appears. This isn't desired behavior unless specifically marked.

Also this is a helpful feature. Renaming so that we save all STDOUT

**Comment by heethjain21** [comment]
Hi @areibman , was looking to resolve this issue.

Can see a branch created by you (with a WIP commit): https://github.com/AgentOps-AI/agentops/tree/350-save-all-logs-from-agentops-runs

Can I take over this issue and resolve it?
