### ISSUE TITLE
AI21 support

### ISSUE THREAD

**Issue by areibman** [AgentOps-AI/agentops#372]
## 🚀 Feature Request

**💡 Got a brilliant idea?**
Support AI21 models through the python SDK

https://docs.ai21.com/docs/python-sdk

**Comment by the-praxs** [comment]
I am working on this one, will open the PR once its ready

**Comment by dot-agi** [comment]
> ## 🚀 Feature Request
> **💡 Got a brilliant idea?** Support AI21 models through the python SDK
> 
> https://docs.ai21.com/docs/python-sdk

Working on this in #382

**Comment by dot-agi** [comment]
> > ## 🚀 Feature Request
> > **💡 Got a brilliant idea?** Support AI21 models through the python SDK
> > https://docs.ai21.com/docs/python-sdk
> 
> Working on this in #382

This is now ready for review!
