### ISSUE TITLE
Support for Semantic Kernel

### ISSUE THREAD

**Issue by juan-trujillo** [AgentOps-AI/agentops#373]
## 🚀 Feature Request
Support for Semantic Kernel as it is now G.A. and it is Enterprise ready.
[Semantic Kernel](https://learn.microsoft.com/en-us/semantic-kernel/overview/)

**Comment by dot-agi** [comment]
I can work on this now @areibman

**Comment by areibman** [comment]
> I can work on this now @areibman

I'm not entirely sure what Semantic Kernel is lol. To be honest it's not the most pressing thing we need as I've not heard a ton of demand for it. By the looks of their GitHub issues, it's mostly used by .NET developers on Windows.

Going to mark this as not planned-- unless there's something specific you're after @juan-trujillo ?

**Comment by dot-agi** [comment]
Closing this in favor of #516
