### ISSUE TITLE
RUN LOCALLY

### ISSUE THREAD

**Issue by jdevsan** [AgentOps-AI/agentops#375]
hi guys its possible to run agentops locally i mean all UI and backend? or i have to use api and python module?

**Comment by areibman** [comment]
> hi guys its possible to run local this? or i need to use API from agentops?

HI @jdevsan -- We can help you with self-hosting if that's a requirement, shoot an email to alex@agentops.ai

**Comment by jdevsan** [comment]
> > hi guys its possible to run local this? or i need to use API from agentops?
> 
> HI @jdevsan -- We can help you with self-hosting if that's a requirement, shoot an email to [alex@agentops.ai](mailto:alex@agentops.ai)

thanks a lot for your response.

**Comment by vinaykhosla-regtech** [comment]
Is self hosting for free?
