### ISSUE TITLE
Agentops is tracking sessions even after I commented out the tracking code

### ISSUE THREAD

**Issue by anmol-aidora** [AgentOps-AI/agentops#376]
## 🐛 Bug Report

**🔎 Describe the Bug**
I have commented out the agentops code in my notebook. But still it is tracking the chat and generating tracking links. 
I have restarted the notebook but still its happening.

**🔄 Reproduction Steps**
Not sure how you would reproduce it.

**🙁 Expected Behavior**
If I comment out the code, it should stop tracking and should not create new sessions.

**📸 Screenshots**
Can't provide screenshots due to company policy.

**🔍 Additional Context**
I was using agentops in my notebook before to track the sessions and it was working well. But even after commenting, its tracking new runs.

**Comment by areibman** [comment]
Can you check your environment variables and make sure that your API key isn't getting loaded in?

**Comment by anmol-aidora** [comment]
API key was getting loaded in, but without agentops.init, it shouldn't start. I have checked [crewAI's code](https://github.com/crewAIInc/crewAI/blob/bc793749a51cbcee21cd1b606e8c5c0adaa8558d/src/crewai/crew.py#L50) and based on that i can concur that if I don't call agentops.init, it shouldn't start recording.

**Comment by braelyn-ai** [comment]
Are you using Crew in your notebook?

**Comment by braelyn-ai** [comment]
Also in a notebook, make sure you restart the interpreter after commenting out `agentops.init()`. Once the client is initialized, it will continue tracking as long as its initialized.

**Comment by anmol-aidora** [comment]
> Are you using Crew in your notebook?

Yes, I am. 

> Also in a notebook, make sure you restart the interpreter after commenting out `agentops.init()`. Once the client is initialised, it will continue tracking as long as its initialized.

I restarted the notebook every time before running the code. I have been using agentops in my day-to-day work. If this issue comes again, I will make a short video and share here. @bboynton97 Thanks for taking the time to review it. I appreciate it
