### ISSUE TITLE
Add duration + LLM analytics at end of session in CLI

### ISSUE THREAD

**Issue by areibman** [AgentOps-AI/agentops#380]
## 🚀 Feature Request

**💡 Got a brilliant idea?**
Right now, we return total session cost: `🖇 AgentOps: This run's cost $0.00`

Would be awesome if we also show:
* Number of LLM calls
* Number of tool calls
* Total duration of session

**Comment by heethjain21** [comment]
Created a PR: https://github.com/AgentOps-AI/agentops/pull/392

Can add more metrics if needed (for now, just added these 3 additional metrics)
