### ISSUE TITLE
[Bug]: Updating PyYAML, requests, psutil packages to latest version required

### ISSUE THREAD

**Issue by MervinPraison** [AgentOps-AI/agentops#433]
### 📦 Package Version

0.3.12

### 🔎 Describe the Bug

Because crawl4ai (0.3.3) depends on PyYAML (6.0.2)
 and agentops (0.3.12) depends on PyYAML (6.0.1), crawl4ai (0.3.3) is incompatible with agentops (0.3.12).
And because no versions of agentops match >0.3.12, crawl4ai (0.3.3) is incompatible with agentops (>=0.3.12).
So, because praisonai depends on both agentops (>=0.3.12) and crawl4ai (==0.3.3), version solving failed.

Because crawl4ai (0.3.3) depends on requests (2.32.3)
 and agentops (0.3.12) depends on requests (2.31.0), crawl4ai (0.3.3) is incompatible with agentops (0.3.12).
And because no versions of agentops match >0.3.12, crawl4ai (0.3.3) is incompatible with agentops (>=0.3.12).
So, because praisonai depends on both agentops (>=0.3.12) and crawl4ai (==0.3.3), version solving failed.

Because crawl4ai (0.3.3) depends on psutil (6.0.0)
 and agentops (0.3.12) depends on psutil (5.9.8), crawl4ai (0.3.3) is incompatible with agentops (0.3.12).
And because no versions of agentops match >0.3.12, crawl4ai (0.3.3) is incompatible with agentops (>=0.3.12).
So, because praisonai depends on both agentops (>=0.3.12) and crawl4ai (==0.3.3), version solving failed.

### 🤝 Contribution

- [ ] Yes, I'd be happy to submit a pull request with these changes.
- [ ] I need some guidance on how to contribute.
- [X] I'd prefer the AgentOps team to handle this update.

**Comment by areibman** [comment]
@MervinPraison Just raised a PR for this @MervinPraison #434 -- We'll have it in the next release
