### ISSUE TITLE
[Bug]: 🖇 AgentOps: Error: cannot access local variable 'formatted_cost' where it is not associated with a value

### ISSUE THREAD

**Issue by knivore** [AgentOps-AI/agentops#440]
### Contact Details

chinkeh@hotmail.com

### 📦 Package Version

0.3.13

### 🎞️ Framework Version

CrewAI 0.67.1

### 🔎 Describe the Bug

  File "/Users/kehchinleong/Documents/CDWP/project-mata/venv/lib/python3.11/site-packages/agentops/session.py", line 154, in end_session
    f"{colored('Cost:', attrs=['bold'])} ${formatted_cost} "
                                           ^^^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'formatted_cost' where it is not associated with a value

### 🤝 Contribution

- [X] Yes, I'd be happy to submit a pull request with these changes.
- [X] I need some guidance on how to contribute.
- [ ] I'd prefer the AgentOps team to handle this update.

**Comment by knivore** [comment]
Created a PR here. https://github.com/AgentOps-AI/agentops/pull/441

Hope to have some guidance to see if its on the right track and whether what i can further contribute

**Comment by areibman** [comment]
Great fix, thanks @knivore!
