### ISSUE TITLE
[Docs]: Anthropic support docs

### ISSUE THREAD

**Issue by areibman** [AgentOps-AI/agentops#446]
### 📘 Current State of Documentation

We currently don't show how to use the Anthropic SDK in the docs. Update 2 things:
1. Docs page
2. Readme 

### 📖 Suggested Improvement

- Sample code snippet in docs
- Sample code snippet in readme
- Notebook example

### 🤝 Contribution

- [ ] Yes, I'd be happy to submit a pull request with these changes.
- [ ] I need some guidance on how to contribute.
- [ ] I'd prefer the Agentops team to handle this update.

**Comment by TKTSWalker** [comment]
Development started!

I've made three kaggle based journals, they should work elsewhere without issue though! These show how to use the sync, async and tool system! I reference a few things like Nier and Cyberpunk to make them a little more interesting to read (and hopefully easier to understand as well)!

I want to clean up my code for the tool system a little (since I know I make syntax errors here and there, i'm a C# guy), but I plan on doing more examples in relation to both the other requests here and making generic examples (Like saving chat history, local vs online tools and how to make each, etc) later on!

Most importantly, if there is anything you directly want to see as an example for the services please do let me know!

[anthropic-examples.zip](https://github.com/user-attachments/files/17508535/anthropic-examples.zip)

**Comment by areibman** [comment]
> Development started!
> 
> I've made three kaggle based journals, they should work elsewhere without issue though! These show how to use the sync, async and tool system! I reference a few things like Nier and Cyberpunk to make them a little more interesting to read (and hopefully easier to understand as well)!
> 
> I want to clean up my code for the tool system a little (since I know I make syntax errors here and there, i'm a C# guy), but I plan on doing more examples in relation to both the other requests here and making generic examples (Like saving chat history, local vs online tools and how to make each, etc) later on!
> 
> Most importantly, if there is anything you directly want to see as an example for the services please do let me know!
> 
> [anthropic-examples.zip](https://github.com/user-attachments/files/17508535/anthropic-examples.zip)

Awesome, would love to see a PR!

Also, it turns out we have an Anthropic notebook already, but it's not in the docs (docs.agentops.ai) and the one in the readme points to the wrong link

**Comment by TKTSWalker** [comment]
Thank you! I'm going to likely make a singular big request every 3/4 of these I do, for example right now i'm on the Gemini contrib request!

I also saw that journal while dissecting the repo but I felt that it might not be easy enough to understand for someone who's new to LLM development!

**Comment by areibman** [comment]
> Thank you! I'm going to likely make a singular big request every 3/4 of these I do, for example right now i'm on the Gemini contrib request!
> 
> I also saw that journal while dissecting the repo but I felt that it might not be easy enough to understand for someone who's new to LLM development!

Thanks for your contribution! Just a quick note: it’s generally better to make smaller, more frequent pull requests, as they are easier to review and integrate. This approach also helps to ensure that everything stays aligned with the current state of the repo. i.e. 1 branch per pull request per issue

**Comment by dot-agi** [comment]
@TKTSWalker let me know if you need any help with this :)

**Comment by TKTSWalker** [comment]
Thank you both! That makes much more sense compared to what I was thinking of! @the-praxs is there any specific way in which you guys want the journal when pushed? I was thinking of essentially creating a general readable page talking about Anthropic and showing a basic setup before moving onto examples as links directly on the repo or Kaggle!

**Comment by TKTSWalker** [comment]
Before I forget to mention, I made a pull request! I am afraid my syntax might have an issue or two (It didn't on Kaggle but exporting can be a little weird sometimes), if there are any problems or changes you would like to request please let me know!

Also please let me know if the AI guide is something you'd be interested in, i'd love to work on this in general for new AI developers that don't fully understand how things like context, tokens and models work before going onto novel stuff like saving information and recalling while keeping a small context size!

Halfway through on the Gemini side!

**Comment by dot-agi** [comment]
> Before I forget to mention, I made a pull request! I am afraid my syntax might have an issue or two (It didn't on Kaggle but exporting can be a little weird sometimes), if there are any problems or changes you would like to request please let me know!
> 
> Also please let me know if the AI guide is something you'd be interested in, i'd love to work on this in general for new AI developers that don't fully understand how things like context, tokens and models work before going onto novel stuff like saving information and recalling while keeping a small context size!
> 
> Halfway through on the Gemini side!

Thanks for the PR! I am reviewing it right now.

I think a guide would be useful for getting started with these SDKs + how AgentOps comes into practice and helps guide you in your LLM dev journey. Thoughts @areibman?

**Comment by areibman** [comment]
> > Before I forget to mention, I made a pull request! I am afraid my syntax might have an issue or two (It didn't on Kaggle but exporting can be a little weird sometimes), if there are any problems or changes you would like to request please let me know!
> > Also please let me know if the AI guide is something you'd be interested in, i'd love to work on this in general for new AI developers that don't fully understand how things like context, tokens and models work before going onto novel stuff like saving information and recalling while keeping a small context size!
> > Halfway through on the Gemini side!
> 
> Thanks for the PR! I am reviewing it right now.
> 
> I think a guide would be useful for getting started with these SDKs + how AgentOps comes into practice and helps guide you in your LLM dev journey. Thoughts @areibman?

Love that idea @TKTSWalker. Shoot me an email/DM and we can chat about what that might look like
