### ISSUE TITLE
[Feature]: A1 21 First Party Support

### ISSUE THREAD

**Issue by AtomSilverman** [AgentOps-AI/agentops#449]
### 💡 Feature Description and Proposed Solution

https://docs.ai21.com/docs/overview

Looking for first party support similar to https://docs.agentops.ai/v1/integrations/cohere

### 🤝 Contribution

- [ ] Yes, I'd be happy to submit a pull request with these changes.
- [ ] I need some guidance on how to contribute.
- [ ] I'd prefer the AgentOps team to handle this update.

**Comment by areibman** [comment]
Duplicate
