### ISSUE TITLE
[Feature]: Integrate Grok (xAI)

### ISSUE THREAD

**Issue by AtomSilverman** [AgentOps-AI/agentops#452]
### 💡 Feature Description and Proposed Solution

https://docs.x.ai/docs

First party support similar to Cohere. 

### 🤝 Contribution

- [ ] Yes, I'd be happy to submit a pull request with these changes.
- [ ] I need some guidance on how to contribute.
- [ ] I'd prefer the AgentOps team to handle this update.

**Comment by dot-agi** [comment]
@AtomSilverman Anthropic and OpenAI already support this so I will just add a notebook explaining how to use it with our library.
