### ISSUE TITLE
[Docs]: OpenAI documentation

### ISSUE THREAD

**Issue by areibman** [AgentOps-AI/agentops#470]
### 📘 Current State of Documentation

Surprisingly, we have no reference whatsoever to OpenAI. OpenAI is our bread and butter!

### 📖 Suggested Improvement

- Readme section on OpenAI
- Docs page on OpenAI
- OpenAI notebook for a variety of models

### 🤝 Contribution

- [ ] Yes, I'd be happy to submit a pull request with these changes.
- [ ] I need some guidance on how to contribute.
- [ ] I'd prefer the Agentops team to handle this update.

**Comment by TKTSWalker** [comment]
I'll be handling this right now! I'm actually going to put two things here; one is in relation to an AI language generator i've been working on while another will handle making conversation summaries based on the max output length and mood

**Comment by dot-agi** [comment]
> I'll be handling this right now! I'm actually going to put two things here; one is in relation to an AI language generator i've been working on while another will handle making conversation summaries based on the max output length and mood

Handling this in #549, take a look if you want to contribute. Thanks!

**Comment by TKTSWalker** [comment]
No problem and thank you for mentioning me! For pre and post v1, would you rather there be the relatively same 2 examples with changes made to work pre v1 or would you rather prefer 2 entirely different examples? I'm working on some side Supabase stuff for a project of mines, but before next Monday I should have it ready, readmes and all as well as a part of the guide mentioned!

**Comment by dot-agi** [comment]
I prefer the same examples for both since it will be easy for the end-user to understand.

I am creating some example notebooks so feel free to take a look and add your concepts, if required, in the relevant notebooks.

**Comment by TKTSWalker** [comment]
Sounds good! I'll take a look and see what I can do asap!
