### ISSUE TITLE
Relax dependencies requirements

### ISSUE THREAD

**Issue by teocns** [AgentOps-AI/agentops#481]
### 💡 Feature Description and Proposed Solution

Are there any reasons to pin dependencies to an exact version, rather than using ` >= <= ~`?

https://github.com/AgentOps-AI/agentops/blob/f4d834780f42644d276e8d83a7e9e185116f5bc4/pyproject.toml#L22-L27

### 🤔 Related Problem

```
➜  git:(dev) ✗ r sync
Reusing already existing virtualenv
Generating production lockfile: requirements.lock
  × No solution found when resolving dependencies for split (python_full_version < '3.12'):
  ╰─▶ Because you require psutil==5.9.8 and psutil>=6.0.0, we can conclude that your requirements are unsatisfiable.
error: could not write production lockfile for workspace
```

### 🤝 Contribution

- [X] Yes, I'd be happy to submit a pull request with these changes.
- [ ] I need some guidance on how to contribute.
- [ ] I'd prefer the AgentOps team to handle this update.

**Comment by teocns** [comment]
Let's determine whether we really need to enforce pinning those down, git blame is a good place to start, but feedback from peers for any eventual compatibility requirements is appreciated

**Comment by areibman** [comment]
* Requests was an issue for a bunch of frameworks, so that range was necessary
* Packaging might be tricky. Build errors are never fun, so I'd rather stick with something I know works
* PyYaml also had issues with some other frameworks 

The other ones-- I don't see a strong reason not to unpin them, unless there are dramatic convention changes between major versions

**Comment by teocns** [comment]
Going for `psutil` and `termcolor` which is also a potentially breaking package in TUI-powered clients

**Comment by braelyn-ai** [comment]
- packaging pinned breaks agentstack

i had an issue with two others but i dont remember now
