### ISSUE TITLE
[Feature]: Anthropic Computer Use Support

### ISSUE THREAD

**Issue by areibman** [AgentOps-AI/agentops#496]
### 💡 Feature Description and Proposed Solution

https://docs.anthropic.com/en/docs/build-with-claude/computer-use

We currently don't support the beta endpoints: `response = client.beta.messages.create(...)`

### 🤝 Contribution

- [X] Yes, I'd be happy to submit a pull request with these changes.
- [ ] I need some guidance on how to contribute.
- [X] I'd prefer the AgentOps team to handle this update.

**Comment by dot-agi** [comment]
Closed by #497.
