### ISSUE TITLE
[Docs]: Anthropic Tool Usage Documentation Fix

### ISSUE THREAD

**Issue by TKTSWalker** [AgentOps-AI/agentops#499]
### 📘 Current State of Documentation

While working on the documentation for Anthropic, I noticed a few things;

1. There seems to be trouble getting the text as a stream and it instead likes to get the output as a singular item.
2. The base AgentOps reference puts everything into a string but this is wrong; Anthropic uses a block system similar to JSON
3. Multiple blocks may be within, with one being for the AI's text output and another for the tool start
4. Understanding how to use the tools may be one of the hardest things for a newcomer, given it does require understanding context and bringing in the text 1 to 1 may not always be a good idea.

### 📖 Suggested Improvement

I am currently working on an additional journal which

1. Understands the context from the chunk output, showing users how to extract the tool, inputs and AI dialogue
2. Shows how to use the tools in a simple way, while also showing different kinds of output methods
3. Shows the user how to add the context from the tool into the LLM's memory to receive an answer

This should take me about two days to complete, given i'm looking at either doing Ollama's documentation or continuing putting effort towards the Gemini issue!

### 🔗 Affected Documentation Pages

https://github.com/AgentOps-AI/agentops/blob/main/examples/anthropic_examples/anthropic_example.ipynb

https://github.com/AgentOps-AI/agentops/blob/main/examples/anthropic_examples/anthropicguide.md

### 🤝 Contribution

- [X] Yes, I'd be happy to submit a pull request with these changes.
- [ ] I need some guidance on how to contribute.
- [ ] I'd prefer the Agentops team to handle this update.

**Comment by dot-agi** [comment]
Assigning you this issue, address it when you open a PR. Thank you so much!

**Comment by TKTSWalker** [comment]
Hey, I tried pointing to this issue but i'm not sure why it wouldn't work! I made a PR request!
