### ISSUE TITLE
deps: `uv sync --all-extras` fails due to langchain & `python 3.7`

### ISSUE THREAD

**Issue by teocns** [AgentOps-AI/agentops#524]
#### Command Used:
```
uv sync --all-extras
```

#### Error Encountered:
```
Using CPython 3.12.2
Creating virtual environment at: .venv
  × No solution found when resolving dependencies:
  ╰─▶ Because the requested Python version (>=3.7) does not satisfy Python>=3.8 and langchain==0.2.14 depends on Python>=3.8.1,<4.0, we can conclude that langchain==0.2.14 cannot
      be used.
      And because agentops[langchain] depends on langchain==0.2.14 and your project requires agentops[langchain], we can conclude that your projects's requirements are unsatisfiable.

      hint: The `requires-python` value (>=3.7) includes Python versions that are not supported by your dependencies (e.g., langchain==0.2.14 only supports >=3.8.1, <4.0). Consider
      using a more restrictive `requires-python` value (like >=3.8.1, <4.0).
```

### Translation

- `langchain==0.2.14` requires `Python>=3.8`
- Agentops `requires-python >= 3.7` (see [pyproject.toml](https://github.com/AgentOps-AI/agentops/blob/8d58b7f3616bbc529ea6fd704882b3fc78a2578b/pyproject.toml#L16))

### Proposal

To `require-python >= 3.9` which is actually (these times) the "oldest" supported version across most packages

**Comment by teocns** [comment]
cc @areibman high priority for development, I keep stashing `pyproject.toml` 
Mentioning you because this maybe affects a bit the CI ecosystem as well as distribution.
Enforcing `>=3.9` explicitly drops support for `<3.9`, anything that we should know before merging that upstream?
Can we tell the # of clients depending on `<3.9`, if any?

**Comment by areibman** [comment]
Is it possible we only drop support for <3.9 when the `agentops[langchain]` optional dependency is installed? 

Alternatively, given python 3.9 is almost 5 years old, I think it's fair for us to drop it

**Comment by teocns** [comment]
> Is it possible we only drop support for <3.9 when the agentops[langchain] optional dependency is installed?

I think it's possible, and it's a good idea 💡 
Yet I smell side effects and complications

> Alternatively, given python 3.9 is almost 5 years old, I think it's fair for us to drop it

We're dropping support for 3.8 (lower than 3.9)
