### ISSUE TITLE
[Feature]: Adding a dark theme to the main page of the website 

### ISSUE THREAD

**Issue by Gitstar-OC** [AgentOps-AI/agentops#533]
### 💡 Feature Description and Proposed Solution

Hey, I love working on websites and make them better and I would love if I could get the oppurtunity to work on the website and add a dark theme to the main page. (Dark theme to other page exists but it is creating some inconsistency for the homepage) 

Could I get the oppurtunity to work on it ? 

Here's how it will look but better (With the background in black theme) 

https://github.com/user-attachments/assets/8e92c3b9-8402-4310-a8c2-2318f1f7b820

### 🤝 Contribution

- [X] Yes, I'd be happy to submit a pull request with these changes.
- [ ] I need some guidance on how to contribute.
- [ ] I'd prefer the AgentOps team to handle this update.

**Comment by areibman** [comment]
Hey @Gitstar-OC -- we have this queue'd up on our Frontend repo (not open source, I'm afraid). Turns out dark mode is very tricky with our colors, and we've made a custom design and palette for it.

**Comment by Gitstar-OC** [comment]
Well I am waiting for it to drop, the light theme is really sick :)
