### ISSUE TITLE
[Bug]: Stop pinning dependency versions

### ISSUE THREAD

**Issue by braelyn-ai** [AgentOps-AI/agentops#545]
### 📦 Package Version

0.3.18

### 🔎 Describe the Bug

AgentOps dependencies are largely pinned to a specific version (`==`). This is causing issues with projects that depend on AgentOps and use slightly different versions. When possible, use a range (`>=, <=, ^`)

### 🤝 Contribution

- [ ] Yes, I'd be happy to submit a pull request with these changes.
- [ ] I need some guidance on how to contribute.
- [X] I'd prefer the AgentOps team to handle this update.

**Comment by teocns** [comment]
Can ignore: `[dev,ci]`

To be mindful of langchain [(issue here)](https://github.com/search?q=repo%3AAgentOps-AI%2Fagentops+langchain&type=issues):

```
[project.optional-dependencies]
langchain = [
    "langchain==0.2.14; python_version >= '3.8.1'"
]
```
... the same situation applies for `pyvcr`

**Comment by teocns** [comment]
This has been discussed in #481
