### ISSUE TITLE
[Bug]: The new version installation ignore installing llms package

### ISSUE THREAD

**Issue by mehdi262** [AgentOps-AI/agentops#547]
### Contact Details

mehdi.nikkhah@gmail.com

### 📦 Package Version

0.3.19

### 🎞️ Framework Version

Autogen 

### 🔎 Describe the Bug

I uninstalled the older version I had for a conflict with AgentNeo. Installing the latest version of AgentOps raised below error, that indicates it does not have the llms files. Then, I uninstalled the 0.3.19 and installed 0.3.18, which worked again.

Traceback (most recent call last):
  File "C:\Repo\TaskHawk\app_agent_ops.py", line 4, in <module>
    import agentops
  File "C:\Repo\TaskHawk\taskhwak\Lib\site-packages\agentops\__init__.py", line 5, in <module>
    from .client import Client
  File "C:\Repo\TaskHawk\taskhwak\Lib\site-packages\agentops\client.py", line 26, in <module>
    from .llms import LlmTracker
ModuleNotFoundError: No module named 'agentops.llms'

### 🤝 Contribution

- [ ] Yes, I'd be happy to submit a pull request with these changes.
- [ ] I need some guidance on how to contribute.
- [X] I'd prefer the AgentOps team to handle this update.

**Comment by teocns** [comment]
Cannot reproduce
What have you tried?

**Comment by areibman** [comment]
@mehdi262 Would you kindly provide a code snippet, Github gist, or repo link we could look at? Also, you didn't happen to name any files `agentops.py` did you?

**Comment by teocns** [comment]
> Also, you didn't happen to name any files agentops.py did you?

Indeed be careful with files nomenclature. I already see this weird `agentops_init_` which is a good red flag point

**Comment by psyantyst** [comment]
I can reproduce this issue. 
I get the same error when using the latest agentops (0.3.22). When I downgrade agentops to 0.3.18 without any change in my code the error disappears and my code runs just fine.

**Comment by teocns** [comment]
@psyantyst have you tried on a clean environment?

**Comment by psyantyst** [comment]
@teocns yes, I deleted my venv folder and re-installed all dependencies. The error persisted. Once I downgraded agentops to 0.3.18 I no longer got any errors and my sessions were agentops correctly recorded. I haven't tried other agentops versions than the two version I mentioned previously.
