### ISSUE TITLE
[Bug]: Type mismatch in OpenAI example notebook

### ISSUE THREAD

**Issue by BrokenShell** [AgentOps-AI/agentops#548]
### Contact Details

robert@siliconsociety.org

### 📦 Package Version

0.3.19

### 🔎 Describe the Bug

`examples/openai-gpt.ipynb`
There's a type mismatch in the last cell. `ActionEvent` input `params` should be a `dict` but is being sent a `str`.
<img width="623" alt="Screenshot 2024-12-04 at 2 57 25 PM" src="https://github.com/user-attachments/assets/0f46e0c2-2f0e-4f58-a508-f02d0b7f1ecb">

### 🤝 Contribution

- [ ] Yes, I'd be happy to submit a pull request with these changes.
- [ ] I need some guidance on how to contribute.
- [X] I'd prefer the AgentOps team to handle this update.

**Comment by dot-agi** [comment]
Fix merged to main so closing this.
