### ISSUE TITLE
[Docs]: First party support for Mistral AI

### ISSUE THREAD

**Issue by dot-agi** [AgentOps-AI/agentops#550]
### 📘 Current State of Documentation

Currently their [docs](https://docs.mistral.ai/guides/observability/#integration-with-agentops) have a section on integration with AgentOps using CamelAI.

But there is no section explaining first party support.

### 📖 Suggested Improvement

We need to add another section to this page showcasing an example using first party support of the `mistralai` python package.

Link to repo to open a PR -
https://github.com/mistralai/platform-docs-public/blob/main/docs/guides/observability.md

### 🔗 Affected Documentation Pages

https://docs.mistral.ai/guides/observability/#integration-with-agentops

### 🤝 Contribution

- [ ] Yes, I'd be happy to submit a pull request with these changes.
- [ ] I need some guidance on how to contribute.
- [ ] I'd prefer the Agentops team to handle this update.

**Comment by areibman** [comment]
Same as #543
