### ISSUE TITLE
[Bug]: protobuf 5.29.0 has been yanked from pypi

### ISSUE THREAD

**Issue by tcdent** [AgentOps-AI/agentops#553]
### 📦 Package Version

0.3.19

### 🔎 Describe the Bug

`protobuf`== 5.29.0 is no longer available.

https://github.com/protocolbuffers/protobuf/issues/19430#issuecomment-2518458119

### 🤝 Contribution

- [ ] Yes, I'd be happy to submit a pull request with these changes.
- [ ] I need some guidance on how to contribute.
- [ ] I'd prefer the AgentOps team to handle this update.

**Comment by areibman** [comment]
Weird, we don't have protobuf in our pyproject.toml. I wonder why this is happening?

**Comment by tcdent** [comment]
I think it's actually a dependency of a dependency, but I haven't been able to track it down the graph yet.

**Comment by teocns** [comment]
On a clean env:

```
➜  agentops git:(main) uv pip freeze | grep proto               
googleapis-common-protos==1.66.0
opentelemetry-exporter-otlp-proto-common==1.22.0
opentelemetry-exporter-otlp-proto-http==1.22.0
opentelemetry-proto==1.22.0
protobuf==4.24.4
➜  agentops git:(main) uv pip show protobuf      
Name: protobuf
Version: 4.24.4
Location: /Users/beyond/agentops/.venv/lib/python3.12/site-packages
Requires:
Required-by: googleapis-common-protos, opentelemetry-proto
```

Introduced in #529


Try cleaning your environment's cache
