### ISSUE TITLE
Python 3.8 and up use `importlib.metadata`, < 3.8 uses `importlib_metadata`

### ISSUE THREAD

**Issue by teocns** [AgentOps-AI/agentops#615]

**Comment by areibman** [comment]
I suppose we should just officially deprecate <3.8

**Comment by teocns** [comment]
![image](https://github.com/user-attachments/assets/5ea6b0c5-0bc2-4295-83a6-04ac4f6d750e)

**Comment by teocns** [comment]
Fixed in #606
