### ISSUE TITLE
Load tags from env or offer documentation recommendations for how to add different groupings

### ISSUE THREAD

**Issue by areibman** [AgentOps-AI/agentops#7]
## 🚀 Feature Request

**💡 Got a brilliant idea?**
Currently, the highest level grouping of sessions is by session ID. That is, you can't group sessions together other than tags. The problem with tags is that they need to be individually specified for each session instantiation.

As an alternative, I suggest one of the two options:
1) Update the documentation to automatically add tags based on a present environmental variable on-load. For example `AGENTOPS_TAG_GROUP=Chrome navigation test` in the `.env` would automatically add a tag to the tags group.
2) Add another optional argument to the session installation called `group`. For example:
```
        api_key (str): API Key for AgentOps services.
        tags (Dict[str, str], optional): Tags for the sessions that can be used for grouping or sorting later (e.g. {"llm": "GPT-4"}).
        group (str, optional): An ID used to group sessions of the same type together. (e.g. Chrome navigation test).
        config (Configuration, optional): A Configuration object for AgentOps services. If not provided, a default Configuration object will be used.
```

**🤔 Is your feature request related to a problem?**
Currently, we only group sessions by tags in dashboards. It may make sense to have better session grouping logic.

**🎉 Describe the solution you'd like**
Add a way to read env to tags, or add a new optional arg to the agentops instantiation (see above)

**📚 Have you considered any alternatives?**
Grouping by tags alone.

Alternatively, update the documentation to show some recommended practices for using agentops.

**Comment by Alchemist1411** [comment]
Hello,
I would like to give it a try. Can you give a starting point for the issue to ramp things up.

**Comment by areibman** [comment]
> Hello, I would like to give it a try. Can you give a starting point for the issue to ramp things up.

Hi @Alchemist1411 -- this issue is actually pretty stale. I'm going to close it, but this one is a great one to get a start on:
https://github.com/AgentOps-AI/agentops/issues/66

**Comment by Alchemist1411** [comment]
Yeah, sure I'll try
